"""Wire contracts. FROZEN after Phase 1 -- both the fleet and the UI generate from these."""

from attestor_core.protocol.dto import (
    AnswerDto,
    ApprovalRequest,
    ApprovalResponse,
    ArmorEventDto,
    CitationDto,
    CreateReviewRequest,
    HealthResponse,
    QuestionDto,
    ReadyResponse,
    RegistryAgentDto,
    ReviewDetail,
    ReviewSummary,
    SpanDto,
    TraceDto,
    UploadUrlRequest,
    UploadUrlResponse,
)
from attestor_core.protocol.envelope import WorkEnvelope, WorkKind
from attestor_core.protocol.events import (
    AnswerDrafted,
    ArmorBlocked,
    AttestorEvent,
    AwaitingHuman,
    CitationAdded,
    EventEnvelope,
    EventType,
    Heartbeat,
    HumanResolved,
    QuestionTriaged,
    RoundClosed,
    RunCompleted,
    RunFailed,
    RunStarted,
    ToolDenied,
)

__all__ = [
    "AnswerDrafted",
    "AnswerDto",
    "ApprovalRequest",
    "ApprovalResponse",
    "ArmorBlocked",
    "ArmorEventDto",
    "AttestorEvent",
    "AwaitingHuman",
    "CitationAdded",
    "CitationDto",
    "CreateReviewRequest",
    "EventEnvelope",
    "EventType",
    "HealthResponse",
    "Heartbeat",
    "HumanResolved",
    "QuestionDto",
    "QuestionTriaged",
    "ReadyResponse",
    "RegistryAgentDto",
    "ReviewDetail",
    "ReviewSummary",
    "RoundClosed",
    "RunCompleted",
    "RunFailed",
    "RunStarted",
    "SpanDto",
    "ToolDenied",
    "TraceDto",
    "UploadUrlRequest",
    "UploadUrlResponse",
    "WorkEnvelope",
    "WorkKind",
]
